# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: hollow-kionite-nvidia
description: A custom fedora kionite build meant for my gaming pc
base-image: ghcr.io/ublue-os/kinoite-nvidia
image-version: 43

platforms:
  - linux/amd64

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo

    install:
      packages:
        - fzf
        - zsh
        - ruby
        - ruby-devel
        - hyfetch
        - fastfetch
        - tailscale
        - mediawriter
        - cpu-x
        - kcalc
        - kcharselect
        - ksystemlog
        - kdf
        - spectacle
        - okular
        - gwenview
        - gnome-disk-utility

    remove:
      packages:
        - firefox
        - firefox-langpacks
        - kde-partitionmanager

  - type: script
    snippets:
      # Install RPM Fusion (single line ONLY)
      - dnf5 install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

      # Chrome
      - dnf5 install -y https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm

      # Steam + Discord
      - dnf5 install -y steam discord

      # Colorls (temporary build tools)
      - dnf5 install -y @development-tools
      - gem install colorls
      - dnf5 remove -y @development-tools

      # Enable services
      - systemctl enable tailscaled
      
  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system

        remotes:
          - name: flathub
            url: https://dl.flathub.org/repo/flathub.flatpakrepo

          - name: fedora
            url: https://registry.fedoraproject.org
            type: oci
            gpg-verify: false

        install:
          - com.github.tchx84.Flatseal
          - it.mijorus.gearlever
          - com.usebottles.bottles
          - org.kde.kweather
          - org.kde.kate
          - org.kde.okular
          - org.kde.gwenview

  - type: signing
